apiVersion: 1
groups:
    - orgId: 1
      name: Memory
      folder: Memory
      interval: 1m
      rules:
        - uid: b4a1b669-7ddf-46da-a852-a3b43ef7b10b
          title: System Memory Usage (MB)
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: f3fa18d9-8e09-4777-b722-f8da6f71ae4f
              model:
                aggregation: ""
                command: ts.get
                cypher: ""
                datasource:
                    type: redis-datasource
                    uid: f3fa18d9-8e09-4777-b722-f8da6f71ae4f
                field: ""
                filter: ""
                intervalMs: 1000
                keyName: performancedata
                legend: ""
                maxDataPoints: 43200
                path: ""
                query: ""
                refId: A
                streaming: true
                streamingDataType: DataFrame
                streamingInterval: 1000
                type: timeSeries
                value: ""
            - refId: C
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 7000
                            - 0
                        type: gt
                      operator:
                        type: when
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: ""
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: classic_conditions
          dashboardUid: b55fc8c2-7685-4a3e-91f6-cfadca2c0ad5
          panelId: 1
          noDataState: NoData
          execErrState: OK
          for: 1m
          annotations:
            __dashboardUid__: b55fc8c2-7685-4a3e-91f6-cfadca2c0ad5
            __panelId__: "1"
          isPaused: false
